### ISSUE TITLE
Selection of range of ks in SC3

### ISSUE THREAD

**Issue by cjhatch** [yutongo/QuanTC#1]
Hi, 

Thanks for developing this exciting tool! I am trying to run it on my own dataset, and I'm confused about selecting a range of ks for creating the mean cell-cell similarity matrix. In SC3, I run:

> sce <- sc3.SingleCellExperiment(sce, ks = NULL, k_estimator = T)

This provides me a single estimate for the ks. How do I go about selecting a range from this single value? Do I need to run multiple iterations with various ranges for the ks and determine it based on downstream analysis, or is there a way to select them?

I apologize if this is covered in the paper or on GitHub. I skimmed them, but I didn't find anything. 

Thanks!

**Comment by yutongo** [comment]
> Hi,
> 
> Thanks for developing this exciting tool! I am trying to run it on my own dataset, and I'm confused about selecting a range of ks for creating the mean cell-cell similarity matrix. In SC3, I run:
> 
> > sce <- sc3.SingleCellExperiment(sce, ks = NULL, k_estimator = T)
> 
> This provides me a single estimate for the ks. How do I go about selecting a range from this single value? Do I need to run multiple iterations with various ranges for the ks and determine it based on downstream analysis, or is there a way to select them?
> 
> I apologize if this is covered in the paper or on GitHub. I skimmed them, but I didn't find anything.
> 
> Thanks!

Hi,

To cluster your data in the range of ks (the number of clusters) from 2 to 4: sc3(sce, ks = 2:4)
Also, you can find the manual of sc3 here: http://bioconductor.org/packages/release/bioc/vignettes/SC3/inst/doc/SC3.html

**Comment by cjhatch** [comment]
Excellent, thanks!
